-- DROP DATABASE PROCEDURE
CREATE PROCEDURE [dbo].[DELETING_VM]
    @CITY VARCHAR(100),
    @RESULT INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SQL NVARCHAR(MAX);

	-- Check if the Database name you have typed exists
    IF EXISTS (SELECT * FROM DBRecords WHERE DBName = @CITY)
    BEGIN
		SET @SQL = 'DROP DATABASE ' + @CITY;

		EXECUTE sp_executesql @SQL;

		SET @SQL = 'DELETE FROM DBRecords WHERE WHERE DBName = ' + @CITY

		PRINT'DONE';
	END
	ELSE 
	BEGIN
		SET @RESULT = -1
		PRINT 'THERE IS NO DATABASE WITH THIS NAME. PLEASE CHECK YOUR INSERT TEXT AGAIN THANKS!';
	END
END;